# generated by cross-repo/automation, do not edit
project = "konradodwrot/resume-md-pdf"

CONFIGS_REF             = "v0.0.18"
MISC_REF                = "v0.0.31"
OCI_IMAGES_CI_LINUX_REF = "v0.0.128"
PROSE_ASSETS_REF        = "v0.0.61"
PROSE_SPEC_REF          = "v0.0.32"
