# generated by cross-repo/automation, do not edit
project = "konradodwrot/ai-harness/ai-tools-configs"

CENTRALIZED_ASSETS_GENERIC_REF  = "v0.0.12"
CENTRALIZED_ASSETS_PROSE_AI_REF = "v0.0.2"
CHE_SCHEMA_REF                  = "v0.0.9-che-min-v0.0.114"
OCI_IMAGES_CI_LINUX_REF         = "v0.0.155"
PROSE_SPEC_REF                  = "v0.0.32"
