# generated by cross-repo/automation, do not edit
project = "konradodwrot/ai-harness/ai-tools-configs"

CHE_SCHEMA_REF          = "v0.0.1-che-min-v0.0.96"
MISC_REF                = "v0.0.40"
OCI_IMAGES_CI_LINUX_REF = "v0.0.128"
PROSE_ASSETS_REF        = "v0.0.69"
PROSE_SPEC_REF          = "v0.0.32"
