# generated by cross-repo/automation, do not edit
project = "konradodwrot/cross-repo/infra/oci-images"

AI_CONFIGS_REF          = "v0.0.1"
GO_MODULES_CHE_REF      = "che/v0.0.94"
IAC_REF                 = "v0.0.19"
MISC_REF                = "v0.0.23"
OCI_IMAGES_CI_LINUX_REF = "v0.0.124"
PROSE_ASSETS_REF        = "v0.0.60"
PROSE_SPEC_REF          = "v0.0.31"
