# generated by cross-repo/automation, do not edit
project = "konradodwrot/cross-repo/infra/oci-images"

AI_TOOLS_CONFIGS_REF = "v0.0.1"
CHE_SCHEMA_REF       = "v0.0.1-che-min-v0.0.96"
GO_MODULES_CHE_REF   = "che/v0.0.96"
MISC_REF             = "v0.0.40"
PROSE_ASSETS_REF     = "v0.0.69"
PROSE_SPEC_REF       = "v0.0.32"
