# generated by cross-repo/automation, do not edit
project = "konradodwrot/che-packages"

CHE_PACKAGES_SCHEMA_REF      = "v0.0.1-che-min-v0.0.96"
CHE_SCHEMA_REF               = "v0.0.1-che-min-v0.0.96"
OCI_IMAGES_CI_LINUX_DIND_REF = "v0.0.128"
OCI_IMAGES_CI_LINUX_REF      = "v0.0.128"
PROSE_SPEC_REF               = "v0.0.32"
