# generated by cross-repo/automation, do not edit
project = "konradodwrot/che-packages"

CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.19"
CHE_PACKAGES_SCHEMA_REF        = "v0.0.1-che-min-v0.0.96"
CHE_SCHEMA_REF                 = "v0.0.11-che-min-v0.0.120"
OCI_IMAGES_CI_LINUX_DIND_REF   = "v0.0.158"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.158"
PROSE_SPEC_REF                 = "v0.0.37"
