# generated by cross-repo/automation, do not edit
project = "konradodwrot/cross-repo/infra/iac"

AI_TOOLS_CONFIGS_REF    = "v0.0.1"
OCI_IMAGES_CI_LINUX_REF = "v0.0.152"
PROSE_SPEC_REF          = "v0.0.32"
