# generated by cross-repo/automation, do not edit
project = "konradodwrot/ai-harness/sandbox"

AI_TOOLS_CONFIGS_REF           = "v0.0.5"
CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.4"
CHE_SCHEMA_REF                 = "v0.0.1-che-min-v0.0.96"
GO_MODULES_CHE_REF             = "che/v0.0.96"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.128"
PROSE_SPEC_REF                 = "v0.0.32"
TOOLS_CONFIGS_REF              = "v0.0.18"
