# generated by cross-repo/automation, do not edit
project = "konradodwrot/ai-harness/sandbox"

AI_TOOLS_CONFIGS_REF               = "v0.0.11"
CENTRALIZED_ASSETS_GENERIC_REF     = "v0.0.22"
CENTRALIZED_ASSETS_PROSE_AI_REF    = "v0.0.6"
CENTRALIZED_ASSETS_PROSE_HUMAN_REF = "v0.0.20"
CHE_SCHEMA_REF                     = "v0.0.11-che-min-v0.0.120"
GO_MODULES_CHE_REF                 = "che/v0.0.120"
OCI_IMAGES_CI_LINUX_REF            = "v0.0.158"
TOOLS_CONFIGS_REF                  = "v0.0.29"
