# generated by cross-repo/automation, do not edit
project = "konradodwrot/notes"

AI_TOOLS_CONFIGS_REF           = "v0.0.9"
CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.19"
CHE_SCHEMA_REF                 = "v0.0.11-che-min-v0.0.120"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.158"
PROSE_SPEC_REF                 = "v0.0.37"
