# generated by cross-repo/automation, do not edit
project = "konradodwrot/go-modules"

AI_TOOLS_CONFIGS_REF         = "v0.0.1"
CHE_PACKAGES_REF             = "0.0.18"
MISC_REF                     = "v0.0.39"
OCI_IMAGES_CI_LINUX_DIND_REF = "v0.0.128"
OCI_IMAGES_CI_LINUX_REF      = "v0.0.128"
PROSE_ASSETS_REF             = "v0.0.68"
PROSE_SPEC_REF               = "v0.0.32"
