# generated by cross-repo/automation, do not edit
project = "konradodwrot/go-modules"

AI_TOOLS_CONFIGS_REF                = "v0.0.9"
CENTRALIZED_ASSETS_GENERIC_REF      = "v0.0.19"
CENTRALIZED_ASSETS_PROSE_COMMON_REF = "v0.0.5"
CENTRALIZED_ASSETS_PROSE_HUMAN_REF  = "v0.0.13"
CHE_PACKAGES_REF                    = "v0.0.22"
OCI_IMAGES_CI_LINUX_DIND_REF        = "v0.0.158"
OCI_IMAGES_CI_LINUX_REF             = "v0.0.158"
PROSE_SPEC_REF                      = "v0.0.37"
