# generated by cross-repo/automation, do not edit
project = "konradodwrot/cross-repo/automation"

AI_TOOLS_CONFIGS_REF                = "v0.0.8"
CENTRALIZED_ASSETS_GENERIC_REF      = "v0.0.12"
CENTRALIZED_ASSETS_PROSE_AI_REF     = "v0.0.2"
CENTRALIZED_ASSETS_PROSE_COMMON_REF = "v0.0.2"
CENTRALIZED_ASSETS_PROSE_HUMAN_REF  = "v0.0.5"
CHE_SCHEMA_REF                      = "v0.0.9-che-min-v0.0.114"
OCI_IMAGES_CI_LINUX_REF             = "v0.0.156"
PROSE_SPEC_REF                      = "v0.0.32"
