# generated by cross-repo/automation, do not edit
project = "konradodwrot/cross-repo/automation"

AI_TOOLS_CONFIGS_REF           = "v0.0.1"
CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.7"
CHE_SCHEMA_REF                 = "v0.0.1-che-min-v0.0.96"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.128"
PROSE_SPEC_REF                 = "v0.0.32"
