# generated by cross-repo/automation, do not edit
project = "konradodwrot/cross-repo/misc"

AI_TOOLS_CONFIGS_REF    = "v0.0.9"
CHE_SCHEMA_REF          = "v0.0.11-che-min-v0.0.120"
OCI_IMAGES_CI_LINUX_REF = "v0.0.158"
PROSE_ASSETS_REF        = "v0.0.69"
PROSE_SPEC_REF          = "v0.0.37"
