# generated by cross-repo/automation, do not edit
project = "konradodwrot/centralized/assets/prose/common"

CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.22"
CHE_SCHEMA_REF                 = "v0.0.11-che-min-v0.0.120"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.158"
