# generated by cross-repo/automation, do not edit
project = "konradodwrot/user-ssh-util"

AI_TOOLS_CONFIGS_REF           = "v0.0.5"
CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.12"
CHE_SCHEMA_REF                 = "v0.0.9-che-min-v0.0.114"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.155"
PROSE_SPEC_REF                 = "v0.0.32"
