##[>] 🤖🤖
{{- /* rendered once per consumer repo by cross-repo/automation, from repo + depends_on */ -}}
# generated by cross-repo/automation, do not edit
project = "konradodwrot/{{ .repo }}"

{{ range .variables }}
{{- .key }} = "{{ .version }}"
{{ end -}}
##[<] 🤖🤖
