# generated by cross-repo/automation, do not edit
project = "konradodwrot/centralized/assets/generic"

CENTRALIZED_ASSETS_PROSE_AI_REF     = "v0.0.2"
CENTRALIZED_ASSETS_PROSE_COMMON_REF = "v0.0.2"
CENTRALIZED_ASSETS_PROSE_HUMAN_REF  = "v0.0.2"
CHE_SCHEMA_REF                      = "v0.0.6-che-min-v0.0.110"
OCI_IMAGES_CI_LINUX_REF             = "v0.0.152"
