# generated by cross-repo/automation, do not edit
project = "konradodwrot/centralized/assets/prose/ai"

CENTRALIZED_ASSETS_GENERIC_REF = "v0.0.16"
CHE_SCHEMA_REF                 = "v0.0.9-che-min-v0.0.114"
OCI_IMAGES_CI_LINUX_REF        = "v0.0.156"
