# generated by cross-repo/automation, do not edit
project = "konradodwrot/tools-configs"

AI_TOOLS_CONFIGS_REF    = "v0.0.5"
AUTOMATION_REF          = "v0.0.36"
CHE_PACKAGES_REF        = "v0.0.21"
CHE_SCHEMA_REF          = "v0.0.1-che-min-v0.0.96"
GO_MODULES_CHE_REF      = "che/v0.0.96"
MISC_REF                = "v0.0.44"
OCI_IMAGES_CI_LINUX_REF = "v0.0.128"
PROSE_ASSETS_REF        = "v0.0.69"
PROSE_SPEC_REF          = "v0.0.32"
