# generated by cross-repo/automation, do not edit
project = "konradodwrot/tools-configs"

AI_TOOLS_CONFIGS_REF               = "v0.0.5"
AUTOMATION_REF                     = "v0.0.36"
CENTRALIZED_ASSETS_GENERIC_REF     = "v0.0.7"
CENTRALIZED_ASSETS_PROSE_HUMAN_REF = "v0.0.1"
CHE_PACKAGES_REF                   = "v0.0.21"
CHE_SCHEMA_REF                     = "v0.0.1-che-min-v0.0.96"
GO_MODULES_CHE_REF                 = "che/v0.0.96"
OCI_IMAGES_CI_LINUX_REF            = "v0.0.128"
PROSE_SPEC_REF                     = "v0.0.32"
